# Generated by Django 5.0.6 on 2024-09-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cineprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.TextField()),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('cast', models.ManyToManyField(related_name='movie_cast', to='movie_app.cineprof')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movie_app.cineprof')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_producer', to='movie_app.cineprof')),
            ],
        ),
        migrations.CreateModel(
            name='Moviereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_review', to='movie_app.movie')),
            ],
        ),
    ]
